version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12

commands:
  restore-cache:
    description: "Restores Cache"
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

jobs:
  install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore-cache
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/app
          paths: .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore-cache
      - run:
          name: Lint
          command: yarn lint

workflows:
  version: 2
  lint-tsc:
    jobs:
      - install:
          filters:
            branches:
              ignore: master
      - lint:
          requires:
            - install
